-- iCare -> GCI  DRY-RUN — FINAL SCOPE   (STRICTLY READ-ONLY: 2 independent SELECT blocks, writes nothing, needs no new columns)
-- Source : public.icare_snapshots (id='v1') -> data->'kv' -> ICARE_INTERNAL_TASKS_V1 (+ sizes of ICARE_PROJECTS_V1 / ICARE_HISTORY_V1 for the guards)
-- Run D1 and D2 separately in the Supabase SQL Editor — the editor shows only the last result of a run.
-- GENERATED by tools/build-icare-sql.mjs from the same rule set as 10_apply_batch.sql. Do not edit one without the other.

-- ═══════════════════════════════ [D1] ═══════════════════════════════
-- D1 summary — FINAL SCOPE: only the 3 internal tasks migrate. Everything else is reported so the guards in 10_apply_batch.sql have something to compare with.
with snap as (select data->'kv' as kv from public.icare_snapshots where id = 'v1'),

-- source sizes (used only as guards: the snapshot must still look exactly like the approved dry-run)
src as (
  select
    jsonb_array_length(case when jsonb_typeof(kv->'ICARE_INTERNAL_TASKS_V1') = 'array' then kv->'ICARE_INTERNAL_TASKS_V1' else '[]'::jsonb end) as src_tasks,
    jsonb_array_length(case when jsonb_typeof(kv->'ICARE_PROJECTS_V1') = 'array' then kv->'ICARE_PROJECTS_V1' else '[]'::jsonb end) as src_projects,
    (select coalesce(sum(jsonb_array_length(case when jsonb_typeof(p->'projectFollowUps') = 'array' then p->'projectFollowUps' else '[]'::jsonb end)), 0)
       from jsonb_array_elements(case when jsonb_typeof(kv->'ICARE_PROJECTS_V1') = 'array' then kv->'ICARE_PROJECTS_V1' else '[]'::jsonb end) p)::int as src_followups,
    jsonb_array_length(case when jsonb_typeof(kv->'ICARE_HISTORY_V1') = 'array' then kv->'ICARE_HISTORY_V1' else '[]'::jsonb end) as src_history
  from snap),

-- ───────── internal tasks ─────────
t as (select x.value j, x.ordinality::int n from snap, jsonb_array_elements(case when jsonb_typeof(kv->'ICARE_INTERNAL_TASKS_V1') = 'array' then kv->'ICARE_INTERNAL_TASKS_V1' else '[]'::jsonb end) with ordinality x),
t2 as (
  select n, j, j->>'id' legacy_id, nullif(btrim(j->>'title'), '') title, nullif(btrim(j->>'owner'), '') owner, j->>'status' status_raw, j->>'category' category,
         j->>'dueDate' due_raw,
         case when j->>'dueDate' ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])' then left(j->>'dueDate', 10) end due_iso
  from t),
t3 as (
  select t2.*,
    count(*) over (partition by legacy_id) > 1 and row_number() over (partition by legacy_id order by n) > 1 as dup_in_snapshot,
    -- deliberately STRICT: any existing task with the same title (case-insensitive, any due date, any source) counts as a duplicate. The apply guard demands 0
    -- duplicates, so a title collision can only make the run abort for review — never let a duplicate through (this also covers an earlier iCare batch).
    exists (select 1 from public.executive_tasks e where lower(btrim(e.title)) = lower(t2.title)) as nat_dup,
    (t2.status_raw is distinct from '已完成' and t2.due_iso is not null
       and t2.due_iso < to_char((now() at time zone 'Asia/Dubai')::date, 'YYYY-MM-DD')) as past_due_open,
    case t2.category when '财务' then 'COMPANY_ADMIN' when '行政' then 'COMPANY_ADMIN' when '采购' then 'TRADE' when '销售' then 'TRADE' else 'OTHER' end as business_area_will_be,
    case t2.status_raw when '进行中' then 'in_progress' when '等待他人' then 'in_progress' when '已完成' then 'completed' else 'open' end as status_will_be,
    coalesce(nullif(btrim(t2.j->>'blocker'), ''), case when t2.status_raw = '等待他人' then '等待他人（自 iCare 迁移，原无阻塞说明）' end) as blocker_will_be
  from t2),
t4 as (
  select t3.*, case when title is null then 'blocked_no_title'
                    when dup_in_snapshot or nat_dup then 'skip_duplicate'
                    else 'migrate' end as verdict
  from t3)
select section, metric, value from (
  select 'internal tasks -> executive_tasks' section, x.key metric, x.value::int as value, 1 o from (select jsonb_build_object(
      '01 source rows', count(*), '02 will migrate', count(*) filter (where verdict = 'migrate'),
      '03 existing duplicate (skipped)', count(*) filter (where verdict = 'skip_duplicate'), '04 blocked: no title', count(*) filter (where verdict = 'blocked_no_title'),
      '05 info: missing owner', count(*) filter (where owner is null), '06 info: due date unparseable', count(*) filter (where due_raw is not null and btrim(due_raw) <> '' and due_iso is null),
      '07 open tasks with a PAST due date -> due_at will be CLEARED', count(*) filter (where verdict = 'migrate' and past_due_open),
      '08 will be business_area COMPANY_ADMIN', count(*) filter (where verdict = 'migrate' and business_area_will_be = 'COMPANY_ADMIN'),
      '09 will be business_area TRADE', count(*) filter (where verdict = 'migrate' and business_area_will_be = 'TRADE'),
      '10 will be business_area OTHER', count(*) filter (where verdict = 'migrate' and business_area_will_be = 'OTHER'),
      '11 will be status completed', count(*) filter (where verdict = 'migrate' and status_will_be = 'completed'),
      '12 will be status in_progress (incl. waiting-for-others)', count(*) filter (where verdict = 'migrate' and status_will_be = 'in_progress'),
      '13 will be status open', count(*) filter (where verdict = 'migrate' and status_will_be = 'open')) m from t4) q, jsonb_each_text(q.m) x
  union all
  select 'NOT migrated (decision)', x.key, x.value::int, 2 from (select jsonb_build_object(
      '01 projects (source rows) — all skipped', coalesce((select src_projects from src), 0), '02 projectFollowUps (source rows) — all skipped', coalesce((select src_followups from src), 0),
      '03 history (source rows) — reconciliation only', coalesce((select src_history from src), 0)) m) q, jsonb_each_text(q.m) x
  union all
  select 'target tables NOW (guard baseline)', x.key, x.value::int, 3 from (select jsonb_build_object(
      '01 executive_tasks', (select count(*) from public.executive_tasks), '02 crm_projects', (select count(*) from public.crm_projects),
      '03 crm_followups', (select count(*) from public.crm_followups)) m) q, jsonb_each_text(q.m) x
) s order by o, metric;

-- ═══════════════════════════════ [D2] ═══════════════════════════════
-- D2 the internal tasks, one row each, with what each will become
with snap as (select data->'kv' as kv from public.icare_snapshots where id = 'v1'),

-- source sizes (used only as guards: the snapshot must still look exactly like the approved dry-run)
src as (
  select
    jsonb_array_length(case when jsonb_typeof(kv->'ICARE_INTERNAL_TASKS_V1') = 'array' then kv->'ICARE_INTERNAL_TASKS_V1' else '[]'::jsonb end) as src_tasks,
    jsonb_array_length(case when jsonb_typeof(kv->'ICARE_PROJECTS_V1') = 'array' then kv->'ICARE_PROJECTS_V1' else '[]'::jsonb end) as src_projects,
    (select coalesce(sum(jsonb_array_length(case when jsonb_typeof(p->'projectFollowUps') = 'array' then p->'projectFollowUps' else '[]'::jsonb end)), 0)
       from jsonb_array_elements(case when jsonb_typeof(kv->'ICARE_PROJECTS_V1') = 'array' then kv->'ICARE_PROJECTS_V1' else '[]'::jsonb end) p)::int as src_followups,
    jsonb_array_length(case when jsonb_typeof(kv->'ICARE_HISTORY_V1') = 'array' then kv->'ICARE_HISTORY_V1' else '[]'::jsonb end) as src_history
  from snap),

-- ───────── internal tasks ─────────
t as (select x.value j, x.ordinality::int n from snap, jsonb_array_elements(case when jsonb_typeof(kv->'ICARE_INTERNAL_TASKS_V1') = 'array' then kv->'ICARE_INTERNAL_TASKS_V1' else '[]'::jsonb end) with ordinality x),
t2 as (
  select n, j, j->>'id' legacy_id, nullif(btrim(j->>'title'), '') title, nullif(btrim(j->>'owner'), '') owner, j->>'status' status_raw, j->>'category' category,
         j->>'dueDate' due_raw,
         case when j->>'dueDate' ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])' then left(j->>'dueDate', 10) end due_iso
  from t),
t3 as (
  select t2.*,
    count(*) over (partition by legacy_id) > 1 and row_number() over (partition by legacy_id order by n) > 1 as dup_in_snapshot,
    -- deliberately STRICT: any existing task with the same title (case-insensitive, any due date, any source) counts as a duplicate. The apply guard demands 0
    -- duplicates, so a title collision can only make the run abort for review — never let a duplicate through (this also covers an earlier iCare batch).
    exists (select 1 from public.executive_tasks e where lower(btrim(e.title)) = lower(t2.title)) as nat_dup,
    (t2.status_raw is distinct from '已完成' and t2.due_iso is not null
       and t2.due_iso < to_char((now() at time zone 'Asia/Dubai')::date, 'YYYY-MM-DD')) as past_due_open,
    case t2.category when '财务' then 'COMPANY_ADMIN' when '行政' then 'COMPANY_ADMIN' when '采购' then 'TRADE' when '销售' then 'TRADE' else 'OTHER' end as business_area_will_be,
    case t2.status_raw when '进行中' then 'in_progress' when '等待他人' then 'in_progress' when '已完成' then 'completed' else 'open' end as status_will_be,
    coalesce(nullif(btrim(t2.j->>'blocker'), ''), case when t2.status_raw = '等待他人' then '等待他人（自 iCare 迁移，原无阻塞说明）' end) as blocker_will_be
  from t2),
t4 as (
  select t3.*, case when title is null then 'blocked_no_title'
                    when dup_in_snapshot or nat_dup then 'skip_duplicate'
                    else 'migrate' end as verdict
  from t3)
select legacy_id as icare_task_id, title, j->>'description' as description, category, owner, status_raw as status, due_raw as due_date_raw, verdict,
       business_area_will_be, status_will_be, blocker_will_be,
       case when due_iso is null then 'NULL (no parseable due date)' when past_due_open then 'NULL (cleared: open and already past; original kept in legacy_payload)' else due_iso || ' 09:00 Asia/Dubai (kept)' end as due_at_will_be
from t4 order by n;
