import { FollowUpTask, Project } from './types';

const NOW = new Date().toISOString();
const NEXT = '2026-05-20';

export const ADMIN_IMPORT_PROJECTS: Project[] = [
  { id:'PROJ-N-2026002', name:'Ray — 别墅家具及隔断BOQ采购', clientName:'Ray', countryCity:'UAE / Dubai', contactKey:'ray-2026002', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'别墅家具及隔断BOQ，已整理清单，客户在中国，等回迪拜后推进确认。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026003', name:'Kat Maconie OEM 鞋包生产', clientName:'Dr. Heike', countryCity:'UAE', contactKey:'dr-heike-2026003', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'OEM鞋包生产，Kat Maconie品牌，报价中（2026-04-25）。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026004', name:'阿布扎比别墅起居室翻修项目', clientName:'khamis', countryCity:'UAE / Abu Dhabi', contactKey:'khamis-2026004', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'新询盘', initialContext:'阿布扎比别墅起居室翻修，客户失联中。2026-05-08：持续跟进。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026005', name:'项目待补充（2026-005）', clientName:'Mohammed', countryCity:'UAE', contactKey:'mohammed-2026005', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'新询盘', initialContext:'项目详情待补充。2026-05-08：客户未回复，持续跟进。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026007', name:'项目待补充（2026-007 | Ivy）', clientName:'Ivy', countryCity:'UAE', contactKey:'ivy-2026007', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'施工类项目。2026-05-08：追迹客户安排参观施工现场时间。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026008', name:'SOBHA Hartland 2 — 别墅精装工程', clientName:'AL ETEFAQ（SOBHA）', countryCity:'UAE / Dubai', contactKey:'al-etefaq-sobha-2026008', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'执行中', initialContext:'SOBHA Hartland 2别墅精装，AL ETEFAQ。2026-05-08：跟进劳工ID办理进度，确认数量足够后再推进。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026009', name:'土耳其小礼品采购项目', clientName:'土耳其礼品客户', countryCity:'UAE', contactKey:'turkey-gift-2026009', phoneE164:'', whatsapp:'', email:'', type:'贸易型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'土耳其小礼品。2026-05-08：客户要求GCI承担45%进口关税，利润无法覆盖，协商中。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026011', name:'50人营地家具采购项目', clientName:'营地业主（待确认）', countryCity:'UAE', contactKey:'camp-furniture-2026011', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'50人营地家具，供应商含税报价166,398.75 AED。2026-05-12：等待客户确认。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026012', name:'阿布扎比别墅家具采购项目', clientName:'阿布扎比别墅业主（待确认）', countryCity:'UAE / Abu Dhabi', contactKey:'villa-furniture-abu-2026012', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'待报价', initialContext:'别墅家具，报价单QT-2026-001（19条明细），主供应商Casa Bravo，客户预算约AED 277,275。2026-05-12：追迹供应商报价。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026013', name:'Shalini 卫生纸出口项目 — Barbados', clientName:'Shalini', countryCity:'Barbados（出口）', contactKey:'shalini-2026013', phoneE164:'', whatsapp:'', email:'', type:'贸易型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'卫生纸出口Barbados，私标。规格：20米/180-220张/2层/宽100mm/原浆纸。2026-05-08：规格确认，待提最终报价含logo。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026014', name:'ADNOC 加油站 AI 咖啡机合作项目', clientName:'ADNOC', countryCity:'UAE / Abu Dhabi', contactKey:'adnoc-coffee-2026014', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'ADNOC加油站AI咖啡机合作，通过王旭跟进。2026-05-12：已提交最新PPT，等待客户回复。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026015', name:'CZAR Technical Services — MDF 样品', clientName:'CZAR Technical Services', countryCity:'UAE', contactKey:'czar-mdf-2026015', phoneE164:'', whatsapp:'', email:'', type:'贸易型', owner:'Chris', status:'进行中', tradeStatus:'待报价', initialContext:'MDF样品，联系人Sunil。2026-05-09：样品仓库切割中，尚未发出，客户等待。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-2026016', name:'MBZ Hospital — 第四层管道水电分包', clientName:'Ravi（MBZ Hospital）', countryCity:'UAE / Abu Dhabi', contactKey:'mbz-hospital-ravi-2026016', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'执行中', initialContext:'SHK MBZ General Hospital第四层管道工程，水电分包（Ravi）。2026-05-12：WhatsApp跟进。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-SOURCE-TIME', name:'别墅整装项目 — Source Time 投标', clientName:'Source Time（客户待确认）', countryCity:'UAE', contactKey:'source-time-villa', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'已报价待确认', initialContext:'一栋别墅整装，通过Source Time平台投标。详情待补充。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-DHCN', name:'二栋别墅建筑及装修 — DHCN 投标', clientName:'DHCN（客户待确认）', countryCity:'UAE', contactKey:'dhcn-villa', phoneE164:'', whatsapp:'', email:'', type:'项目型', owner:'Chris', status:'进行中', tradeStatus:'新询盘', initialContext:'二栋别墅建筑及装修，通过DHCN投标（2026-04-25）。详情待补充。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
  { id:'PROJ-N-ENGWOOD', name:'Engineered Wood Door 项目', clientName:'（客户待确认）', countryCity:'UAE', contactKey:'engineered-wood-door', phoneE164:'', whatsapp:'', email:'', type:'贸易型', owner:'Chris', status:'进行中', tradeStatus:'新询盘', initialContext:'Engineered wood door采购/贸易，详情待补充（2026-04-27）。', projectFollowUps:[], attachments:[], createdAt:NOW, nextActionAt:NEXT },
];

export const ADMIN_IMPORT_TASKS: FollowUpTask[] = [
  { id:'TASK-N-2026001', leadId:'LEAD-N-2026001', clientName:'Dr. Khalid', phoneE164:'', whatsapp:'', email:'', contactKey:'dr-khalid-2026001', countryCity:'UAE / Sharjah', owner:'Chris', myRole:'SELLER', goal:'等待客户回复是否接受全部施工方案（别墅窗户/屋顶漏水）', lastContext:'2026-04-24 email：客户希望只报材料成本试做1-2窗户，Chris建议一次性完成更划算。2026-05-08：持续等待回复。', businessType:'PROJECT', relatedProjectId:'', status:'todo', tradeStatus:'暂缓', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-001，Project档已存在DEAL，2026-05行动状态已设为暂缓' } as FollowUpTask,
  { id:'TASK-N-2026002', leadId:'LEAD-N-2026002', clientName:'Ray', phoneE164:'', whatsapp:'', email:'', contactKey:'ray-2026002', countryCity:'UAE / Dubai', owner:'Chris', myRole:'SELLER', goal:'联系确认客户回迪拜时间，推进家具及隔断BOQ采购', lastContext:'2026-05-08：联系确认客户回迪拜时间，持续跟进。家具清单BOQ已整理，客户在中国，等回迪拜后推进。', businessType:'PROJECT', relatedProjectId:'', status:'todo', tradeStatus:'已报价待确认', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-002，Project档已存在DEAL' } as FollowUpTask,
  { id:'TASK-N-2026003', leadId:'LEAD-N-2026003', clientName:'Dr. Heike', phoneE164:'', whatsapp:'', email:'', contactKey:'dr-heike-2026003', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'确认Kat Maconie OEM鞋包生产规格与订单细节', lastContext:'项目：Kat Maconie OEM鞋包生产，报价中（2026-04-25）。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026003', status:'todo', tradeStatus:'已报价待确认', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-003' } as FollowUpTask,
  { id:'TASK-N-2026004', leadId:'LEAD-N-2026004', clientName:'khamis', phoneE164:'', whatsapp:'', email:'', contactKey:'khamis-2026004', countryCity:'UAE / Abu Dhabi', owner:'Chris', myRole:'SELLER', goal:'客户失联，持续尝试联系，了解别墅起居室翻修项目进展', lastContext:'2026-05-08：客户失联，持续跟进了解情况。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026004', status:'todo', tradeStatus:'新询盘', priority:'C', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-004' } as FollowUpTask,
  { id:'TASK-N-2026005', leadId:'LEAD-N-2026005', clientName:'Mohammed', phoneE164:'', whatsapp:'', email:'', contactKey:'mohammed-2026005', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'客户未回复，持续跟进', lastContext:'2026-05-08：客户未回复，持续跟进。项目信息待补充。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026005', status:'todo', tradeStatus:'新询盘', priority:'C', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-005' } as FollowUpTask,
  { id:'TASK-N-2026007', leadId:'LEAD-N-2026007', clientName:'Ivy', phoneE164:'', whatsapp:'', email:'', contactKey:'ivy-2026007', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'追迹客户安排参观施工现场的时间', lastContext:'2026-05-08：追迹客户安排参观施工现场时间。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026007', status:'todo', tradeStatus:'已报价待确认', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-007' } as FollowUpTask,
  { id:'TASK-N-2026008', leadId:'LEAD-N-2026008', clientName:'AL ETEFAQ（SOBHA Hartland 2）', phoneE164:'', whatsapp:'', email:'', contactKey:'al-etefaq-2026008', countryCity:'UAE / Dubai', owner:'Chris', myRole:'SELLER', goal:'跟进劳工ID办理进度，确认数量足够后再推进SOBHA Hartland 2别墅精装工程', lastContext:'2026-05-08：跟进劳工ID办理进度，确认数量足够后再推进。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026008', status:'todo', tradeStatus:'执行中', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-008' } as FollowUpTask,
  { id:'TASK-N-2026009', leadId:'LEAD-N-2026009', clientName:'土耳其礼品客户', phoneE164:'', whatsapp:'', email:'', contactKey:'turkey-gift-2026009', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'协商关税承担方案（客户要求GCI承担45%进口关税，利润无法覆盖）', lastContext:'2026-05-08：客户要求GCI承担土耳其进口关税最高45%，利润无法覆盖，协商中。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026009', status:'todo', tradeStatus:'已报价待确认', priority:'C', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-009' } as FollowUpTask,
  { id:'TASK-N-2026010', leadId:'LEAD-N-2026010', clientName:'Khaled — The Grove', phoneE164:'', whatsapp:'', email:'', contactKey:'khaled-grove-2026010', countryCity:'UAE / Abu Dhabi', owner:'Chris', myRole:'SELLER', goal:'跟进中国样品发运时间，确认到迪拜时间表（The Grove Saadiyat Island 金属网吊顶）', lastContext:'2026-05-08：跟进样品从中国发运时间。2026-05-18最新跟进更新。', businessType:'PROJECT', relatedProjectId:'', status:'todo', tradeStatus:'待报价', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-010，Project档已存在DEAL' } as FollowUpTask,
  { id:'TASK-N-2026011', leadId:'LEAD-N-2026011', clientName:'50人营地家具（业主待确认）', phoneE164:'', whatsapp:'', email:'', contactKey:'camp-furniture-2026011', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'追迹客户确认供应商报价（含税166,398.75 AED）', lastContext:'2026-05-08：客户表示已上报，暂无结果。2026-05-12：供应商含税报价166,398.75 AED，等待客户确认。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026011', status:'todo', tradeStatus:'已报价待确认', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-011，金额约166,398.75 AED' } as FollowUpTask,
  { id:'TASK-N-2026012', leadId:'LEAD-N-2026012', clientName:'阿布扎比别墅家具（业主待确认）', phoneE164:'', whatsapp:'', email:'', contactKey:'villa-furniture-2026012', countryCity:'UAE / Abu Dhabi', owner:'Chris', myRole:'SELLER', goal:'追迹Casa Bravo供应商报价进度，收到后第一时间提交客户', lastContext:'2026-05-12：报价单QT-2026-001（19条明细），主供应商Casa Bravo，客户预算约AED 277,275，供应商报价汇总中。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026012', status:'todo', tradeStatus:'待报价', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-012，预算约AED 277,275' } as FollowUpTask,
  { id:'TASK-N-2026013', leadId:'LEAD-N-2026013', clientName:'Shalini', phoneE164:'', whatsapp:'', email:'', contactKey:'shalini-2026013', countryCity:'Barbados（出口）', owner:'Chris', myRole:'SELLER', goal:'提交最终报价含私标logo（卫生纸出口Barbados，规格已确认）', lastContext:'2026-05-08：卷纸规格确认（20米/180-220张/2层/100mm宽/原浆纸），私标logo待价格确认后提供。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026013', status:'todo', tradeStatus:'已报价待确认', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-013' } as FollowUpTask,
  { id:'TASK-N-2026014', leadId:'LEAD-N-2026014', clientName:'ADNOC', phoneE164:'', whatsapp:'', email:'', contactKey:'adnoc-coffee-2026014', countryCity:'UAE / Abu Dhabi', owner:'Chris', myRole:'SELLER', goal:'等待ADNOC回复最新AI咖啡机合作PPT提案', lastContext:'2026-05-09：王旭传递客户反馈。2026-05-12：已正式提交最新PPT，等待客户回复。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026014', status:'todo', tradeStatus:'已报价待确认', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-014，战略级客户' } as FollowUpTask,
  { id:'TASK-N-2026015', leadId:'LEAD-N-2026015', clientName:'CZAR Technical Services', phoneE164:'', whatsapp:'', email:'', contactKey:'czar-mdf-2026015', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'跟进仓库MDF切割进度，确认发样时间后立即通知Sunil', lastContext:'2026-05-09：Sunil需要MDF材料样品，样品仓库切割中，尚未发出，客户等待。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026015', status:'todo', tradeStatus:'待报价', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-015' } as FollowUpTask,
  { id:'TASK-N-2026016', leadId:'LEAD-N-2026016', clientName:'Ravi（MBZ Hospital）', phoneE164:'', whatsapp:'', email:'', contactKey:'mbz-ravi-2026016', countryCity:'UAE / Abu Dhabi', owner:'Chris', myRole:'SELLER', goal:'跟进SHK MBZ Hospital第四层管道水电分包合同与施工安排', lastContext:'2026-05-12：WhatsApp跟进。项目：SHK MBZ General Hospital第四层管道工程，水电分包（Ravi）。', businessType:'PROJECT', relatedProjectId:'PROJ-N-2026016', status:'todo', tradeStatus:'执行中', priority:'A', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 2026-016' } as FollowUpTask,
  { id:'TASK-N-SOURCE-TIME', leadId:'LEAD-N-SOURCE-TIME', clientName:'别墅整装（Source Time）', phoneE164:'', whatsapp:'', email:'', contactKey:'source-time-villa', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'跟进别墅整装投标结果（Source Time平台）', lastContext:'一栋别墅整装项目，通过Source Time平台投标，详情待补充。', businessType:'PROJECT', relatedProjectId:'PROJ-N-SOURCE-TIME', status:'todo', tradeStatus:'已报价待确认', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 项目客户库，编号待确认' } as FollowUpTask,
  { id:'TASK-N-DHCN', leadId:'LEAD-N-DHCN', clientName:'二栋别墅建筑（DHCN投标）', phoneE164:'', whatsapp:'', email:'', contactKey:'dhcn-villa', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'跟进DHCN二栋别墅建筑及装修投标结果', lastContext:'二栋别墅建筑及装修，通过DHCN投标（2026-04-25）。详情待补充。', businessType:'PROJECT', relatedProjectId:'PROJ-N-DHCN', status:'todo', tradeStatus:'新询盘', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 项目客户库，编号待确认' } as FollowUpTask,
  { id:'TASK-N-ENGWOOD', leadId:'LEAD-N-ENGWOOD', clientName:'Engineered Wood Door客户', phoneE164:'', whatsapp:'', email:'', contactKey:'engineered-wood-door', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'跟进Engineered Wood Door采购/贸易项目，补充详情', lastContext:'Engineered wood door采购/贸易，详情待补充（2026-04-27）。', businessType:'PROJECT', relatedProjectId:'PROJ-N-ENGWOOD', status:'todo', tradeStatus:'新询盘', priority:'C', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 项目客户库，编号待确认' } as FollowUpTask,
  { id:'TASK-N-SB001', leadId:'LEAD-N-SB001', clientName:'VLAD', phoneE164:'', whatsapp:'', email:'', contactKey:'vlad-sb001', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'货架已报价300 AED，确认客户是否来Jebel Ali看货，跟进拆卸需求', lastContext:'货架询价报价300（原价1000），已告知Jebel Ali展厅可看货，客户问能否拆卸未完。2026-05-12最新跟进。', businessType:'TRADE', relatedProjectId:'', status:'todo', tradeStatus:'已报价待确认', priority:'C', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 小B/C客户池 SB001' } as FollowUpTask,
  { id:'TASK-N-SB002', leadId:'LEAD-N-SB002', clientName:'Liz Metore International', phoneE164:'', whatsapp:'', email:'', contactKey:'liz-metore-sb002', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'确认尿布municipality备案结果后再跟进报价', lastContext:'2026-05-10：等待尿布municipality备案结果，备案完成后再跟进报价。决策人：uncle/老板。', businessType:'TRADE', relatedProjectId:'', status:'todo', tradeStatus:'已报价待确认', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 小B/C客户池 SB002' } as FollowUpTask,
  { id:'TASK-N-SB003', leadId:'LEAD-N-SB003', clientName:'Rami Kabani', phoneE164:'', whatsapp:'', email:'', contactKey:'rami-kabani-sb003', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'联系Rami先致歉（曾来展厅未被接待），了解需求，判断是否升级为项目客户', lastContext:'⚠️ 曾来展厅未被接待，跟进时须先道歉解释。询价：咖啡豆现货+可能的咖啡机器人合作。需搞清背景再决定方向。2026-05-10。', businessType:'TRADE', relatedProjectId:'', status:'todo', tradeStatus:'新询盘', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 小B/C客户池 SB003，⚠️ 须先道歉' } as FollowUpTask,
  { id:'TASK-N-SB004', leadId:'LEAD-N-SB004', clientName:'k thai 汽配机械贸易', phoneE164:'', whatsapp:'', email:'', contactKey:'k-thai-sb004', countryCity:'UAE（泰国中间商）', owner:'Chris', myRole:'SELLER', goal:'二次跟进UK方是否有意向（6品类GCI报价已发，客户转发英国brother）', lastContext:'已发报价（内衣/浴皂/牙刷/牙膏/太阳能灯/塑料哨子6品类，1500-4500pcs/品类），客户转发UK brother，2026-05-10跟进未回。', businessType:'TRADE', relatedProjectId:'', status:'todo', tradeStatus:'已报价待确认', priority:'B', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 小B/C客户池 SB004' } as FollowUpTask,
  { id:'TASK-N-SB005', leadId:'LEAD-N-SB005', clientName:'diamond horse GTC LLC', phoneE164:'', whatsapp:'', email:'', contactKey:'diamond-horse-sb005', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'5月20日面谈，引导至正品/白牌小商品方向（A货已明确拒绝）', lastContext:'埃及客户，询A货(仿牌)包包/服装，GCI已明确不做A货。已约2026-05-20面谈，引导正品/白牌小商品方向。', businessType:'TRADE', relatedProjectId:'', status:'todo', tradeStatus:'已报价待确认', priority:'B', nextFollowUpAt:'2026-05-20', createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 小B/C客户池 SB005，⚠️ 已约5月20日面谈' } as FollowUpTask,
  { id:'TASK-N-SB006', leadId:'LEAD-N-SB006', clientName:'Merich Global Wholesale LLC', phoneE164:'', whatsapp:'', email:'', contactKey:'merich-global-sb006', countryCity:'UAE', owner:'Chris', myRole:'SELLER', goal:'跟进询价，了解具体品类和量级', lastContext:'2026-05-10：跟进询价，了解具体品类和量级。', businessType:'TRADE', relatedProjectId:'', status:'todo', tradeStatus:'新询盘', priority:'C', nextFollowUpAt:NEXT, createdAt:NOW, updatedAt:NOW, attachments:[], history:[], notes:'Notion 小B/C客户池 SB006' } as FollowUpTask,
];
