import React, { forwardRef } from 'react';
import { createPortal } from 'react-dom';
import { X, Copy, FileDown, Check } from 'lucide-react';
import { colors, logoGradient } from '@gci/design-system';
import type { BankAccount } from '../types';

/**
 * Bank details export (Finance V1, 2026-09) — a client-facing "Company Bank
 * Details" card per Corporate bank_accounts row, with Copy and Export PDF.
 * Read-only presentation of existing bank_accounts fields — does not touch
 * the schema, RLS, balances, or transactions.
 */

const FIELD_ROWS: { label: string; key: keyof BankAccount }[] = [
  { label: 'Company / Account Holder Name', key: 'account_holder_name' },
  { label: 'Bank Name', key: 'bank_name' },
  { label: 'Account Number', key: 'account_number' },
  { label: 'IBAN', key: 'iban' },
  { label: 'SWIFT / BIC', key: 'swift_bic' },
  { label: 'Currency', key: 'currency' },
  { label: 'Bank Address', key: 'bank_address' },
  { label: 'Branch', key: 'branch_name' },
];

export function formatBankDetailsText(account: BankAccount): string {
  const lines = [
    `${account.account_holder_name || account.account_name} — Company Bank Details`,
    '',
    ...FIELD_ROWS.map(({ label, key }) => `${label}: ${(account[key] as string) || '-'}`),
  ];
  return lines.join('\n');
}

/**
 * The printable card itself. Rendered both on-screen (in the view modal)
 * and off-screen (one per account, for "Export All Corporate Accounts") —
 * the same component is what gets captured by html2canvas either way, so
 * there's exactly one visual template to keep in sync, not two.
 */
export const BankDetailsCard = forwardRef<HTMLDivElement, { account: BankAccount }>(
  ({ account }, ref) => (
    <div
      ref={ref}
      style={{
        width: 680,
        background: '#ffffff',
        padding: '56px 64px',
        fontFamily: "'Noto Sans SC', sans-serif",
        color: '#1a1f2e',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, borderBottom: `2px solid ${colors.goldBase}`, paddingBottom: 24, marginBottom: 32 }}>
        <div
          style={{
            width: 44, height: 44, borderRadius: 10, background: logoGradient,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: 18, color: colors.bgBase,
          }}
        >
          G
        </div>
        <div>
          <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: 20, color: '#0F172A', lineHeight: 1.1 }}>
            Global Care Info
          </div>
          <div style={{ fontSize: 10, letterSpacing: '0.18em', color: colors.goldMuted, textTransform: 'uppercase', marginTop: 3 }}>
            Company Bank Details
          </div>
        </div>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse' }}>
        <tbody>
          {FIELD_ROWS.map(({ label, key }) => (
            <tr key={key} style={{ borderBottom: '1px solid #EEF0F4' }}>
              <td style={{ padding: '14px 0', width: '38%', fontSize: 11, fontWeight: 700, letterSpacing: '0.04em', color: '#8A8F9C', textTransform: 'uppercase', verticalAlign: 'top' }}>
                {label}
              </td>
              <td style={{ padding: '14px 0', fontSize: 15, fontWeight: 600, color: '#1a1f2e', wordBreak: 'break-word' }}>
                {(account[key] as string) || <span style={{ color: '#C7CBD4' }}>—</span>}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ marginTop: 40, paddingTop: 20, borderTop: '1px solid #EEF0F4', fontSize: 10, color: '#A0A5B2' }}>
        Generated by GCI Platform on {new Date().toISOString().slice(0, 10)}. For payment purposes only.
      </div>
    </div>
  )
);
BankDetailsCard.displayName = 'BankDetailsCard';

interface BankDetailsModalProps {
  account: BankAccount;
  onClose: () => void;
  onExportPdf: (el: HTMLDivElement, account: BankAccount) => Promise<void>;
}

export function BankDetailsModal({ account, onClose, onExportPdf }: BankDetailsModalProps) {
  const cardRef = React.useRef<HTMLDivElement>(null);
  const [copied, setCopied] = React.useState(false);
  const [exporting, setExporting] = React.useState(false);

  // Lock background page scroll while this modal is mounted (the parent
  // conditionally renders it, so mount/unmount tracks open/close) — same
  // pattern as FinanceTracker's "新增银行账户" modal. Always restored on
  // unmount.
  React.useEffect(() => {
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = prevOverflow;
    };
  }, []);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatBankDetailsText(account));
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch (e) {
      alert('复制失败，请手动选中文本复制。');
    }
  };

  const handleExport = async () => {
    if (!cardRef.current) return;
    setExporting(true);
    try {
      await onExportPdf(cardRef.current, account);
    } catch (e: any) {
      alert(`导出失败：${e?.message || '未知错误'}`);
    } finally {
      setExporting(false);
    }
  };

  // Portal fix (2026-09): mount straight onto document.body so `fixed
  // inset-0` is always anchored to the real viewport, regardless of any
  // ancestor (in FinanceTracker or wherever else this modal is used) that
  // might establish its own containing block for fixed-position elements.
  // Same fix, same reasoning as FinanceTracker's "新增银行账户" modal.
  return createPortal(
    <div className="fixed inset-0 bg-black/70 backdrop-blur-xl z-[6000] flex items-center justify-center p-4 sm:p-8">
      <div
        className="bg-white rounded-[40px] shadow-2xl w-full flex flex-col overflow-hidden"
        style={{ maxHeight: 'calc(100dvh - 32px)', maxWidth: 760 }}
      >
        <div className="shrink-0 flex items-center justify-between px-8 pt-8 pb-5">
          <h3 className="text-sm font-black text-[#080D1E] uppercase tracking-[0.2em]">银行信息 / Bank Details</h3>
          <button onClick={onClose} className="text-gray-300 hover:text-gray-600 shrink-0">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* flex-1 + min-h-0 is load-bearing — see FinanceTracker.tsx's
            "新增银行账户" modal for the full explanation of why this exact
            combination was missing the real fix earlier. */}
        <div className="flex-1 min-h-0 overflow-y-auto px-8 pb-4">
          <div className="border border-gray-100 rounded-2xl overflow-hidden shadow-sm" style={{ transform: 'scale(1)', transformOrigin: 'top left' }}>
            <div style={{ maxWidth: '100%', overflow: 'auto' }}>
              <BankDetailsCard ref={cardRef} account={account} />
            </div>
          </div>
        </div>

        <div className="shrink-0 px-8 pt-5 pb-8 border-t border-gray-100 grid grid-cols-2 gap-3">
          <button
            onClick={handleCopy}
            className="flex items-center justify-center gap-2 py-4 rounded-[20px] bg-gray-100 text-gray-700 font-black text-[10px] uppercase hover:bg-gray-200 transition-all"
          >
            {copied ? <Check className="w-4 h-4 text-[#3F7D58]" /> : <Copy className="w-4 h-4" />}
            {copied ? '已复制' : 'Copy Bank Details'}
          </button>
          <button
            onClick={handleExport}
            disabled={exporting}
            className="flex items-center justify-center gap-2 py-4 rounded-[20px] bg-[#080D1E] text-white font-black text-[10px] uppercase hover:bg-[#CBA85C] transition-all disabled:opacity-40"
          >
            <FileDown className="w-4 h-4" />
            {exporting ? '导出中...' : 'Export PDF'}
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}
